version: "3.9"
services:
  web:
    build: ./web
    restart: always
    volumes:
      - "./web:/var/www/html"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db

  db:
     image: mysql
     restart: always
     env_file: ./.env
     environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${test_db}
     ports:
      - "3308:3306"
  phpmyadmin:
     image: phpmyadmin/phpmyadmin:latest
     restart: always
     env_file: ./.env
     environment:
      PMA_HOST: ${PMA_HOST}
      PMA_USER: ${PMA_USER}
      PMA_PASSWORD: ${PMA_PASSWORD}
     ports:
      - "8080:80"